### ISSUE TITLE
dhcpd.conf is missing the option "domain-name-servers"

### ISSUE THREAD

**Issue by alainvanhoof** [clustervision/luna2-daemon#1]
The internal interface of the nodes is configured to use DHCP and is controlled by the networkmanager.
When provisioning a node the /etc/resolv.conf is in the image:
 
```
000000 14:20:24 [root@hpc-head01 ~]# cat /trinity/images/compute/etc/resolv.conf 
#
# Ansible managed
#

search cluster ipmi
nameserver 10.141.255.254
```

This works until the DHPC lease is refreshed and networkmanager uses the domain-name-servers option to reconfigure /etc/resolv.conf. As the option is missing, this is the result:

```
[root@node002 ~]# cat /etc/resolv.conf 
# Generated by NetworkManager
search cluster
```

**Comment by aphmschonewille** [comment]
solved!

**Comment by aphmschonewille** [comment]
ansible-playbook controller.yml --tags=luna  will pull in latest daemon release with this fix
