### ISSUE TITLE
template for dhcpd.conf is using the option (number 4) "time-servers" not "ntp-servers" (number 42)

### ISSUE THREAD

**Issue by alainvanhoof** [clustervision/luna2-daemon#2]
To set the system time chrony is used. chrony uses the ntp protocol and not the sntp protocol  (https://safran-navigation-timing.com/ntp-vs-sntp-whats-the-difference/). As dhcpd.conf currently sets te time-servers and not the ntp-servers chrony will never pick-up the setting from dhcp.

**Comment by msteggink** [comment]
Indeed, we use chrony for the Linux machines, this is fixed in a future release.

**Comment by aphmschonewille** [comment]
For the time being one could alter the template (/trinity/local/luna/daemon/templates/templ_dhcpd.*) to render the correct option. Restart luna (systemctl restart luna2-daemon) after the change and you're good to go.
